version: "3.3"
services:
  app:
    build: .
    image: Syncthing:rc1
    container_name: Syncthing
    ports: 
      - "8384:8384"
    volumes:
      - "/Syncthing_Docker/Data:/Data"
      - "/Syncthing_Docker/Config:/root/.config/syncthing"